maclay_service_login:
    path:   /
    defaults:   { _controller: MaclayServiceBundle:Account:login }
    methods: [GET]
    
authentication_failed:
    path:   /login
    defaults:   { _controller: MaclayServiceBundle:Account:login }
    methods: [GET]
    
maclay_service_login_full:
    path: /Account/Login
    defaults:   { _controller: MaclayServiceBundle:Account:login }
    methods: [GET]

maclay_service_profile:
    path: /Profile
    defaults: { _controller: MaclayServiceBundle:Profile:profile }
    
addgroup:
    path: /AddGroup
    defaults: { _controller: MaclayServiceBundle:Account:group }
    
recordpartial:
    path: /Record/GetRecordPartial/{id}
    defaults: { _controller: MaclayServiceBundle:Record:getRecordPartial }
    
approverecord:
    path: /Record/ApproveRecord/{id}/{approval}
    defaults: { _controller: MaclayServiceBundle:Record:approveRecord }
    
viewStudent:
    path: /Record/ViewStudent?{id}
    defaults: { _controller: MaclayServiceBundle:Record:viewStudent }
    
resetPassword:
    path: /Account/ResetPassword?{code}
    defaults: { _controller: MaclayServiceBundle:Account:resetPassword }
    
updateCount:
    path: /Admin/UpdateCount?{grade}
    defaults: { _controller: MaclayServiceBundle:Admin:getUninvitedUserCount }
    
getUsersForClub:
    path: /Club/GetUsersForClub/{gender}/{grade}
    defaults: { _controller: MaclayServiceBundle:Club:getUsersForClub }
    
addUserToClub:
    path: /Club/AddUserToClub/{clubId}/{userId}
    defaults: { _controller: MaclayServiceBundle:Club:addUserToClub }

default:
    path: /{controller}/{action}
    defaults: { _controller: MaclayServiceBundle:Routing:route }