maclay_service_login:
    path:   /
    defaults:   { _controller: MaclayServiceBundle:Account:login }
    methods: [GET]
    
maclay_service_login_full:
    path: /Account/Login
    defaults:   { _controller: MaclayServiceBundle:Account:login }
    methods: [GET]

maclay_service_profile:
    path: /Profile
    defaults: { _controller: MaclayServiceBundle:Profile:profile }
    
record_new:
    path: /NewRecord
    defaults: { _controller: MaclayServiceBundle:Record:newRecord }
    
record_create:
    path: /NewRecord/Create
    defaults: { _controller: MaclayServiceBundle:Record:createRecord }
    
addgroup:
    path: /AddGroup
    defaults: { _controller: MaclayServiceBundle:Account:group }