parameters:
    maclay_service.accountservice.class: Maclay\ServiceBundle\Controller\AccountServiceController

services:
    maclay_service.accountservice:
        class: "%maclay_service.accountservice.class%"
