security:
    encoders:
        Maclay\ServiceBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        PARENT:     Parent
        STUDENT:    Student
        TEACHER:    Teacher
        COORDINATOR: [ Parent, Student, Teacher, Coordinator ]
        ADMIN:      [ Coordinator, Admin ]
        

    providers:
        administrators:
            entity: { class: MaclayServiceBundle:User, property: username } 

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }