security:
    encoders:
        Maclay\ServiceBundle\Entity\User:
            algorithm: bcrypt

    acl:
        connection: default
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                failure_path: fos_user_security_login
            logout: 
                path: fos_user_security_logout
                
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }