<?php

namespace Maclay\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. **Not in use.**
 */
class ClubRepository extends EntityRepository
{
    public function getAllClubs(){
        $query = $this->getEntityManager()
                ->createQuery(
                        "SELECT c "
                        . "FROM MaclayServiceBundle:Club c "
                  )
                ->getResult();
        return $query;
    }
}
