<?php

namespace Maclay\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends EntityRepository
{
    
    public function getRecentRecords($length, $userId){
        return $this->getEntityManager()
                ->createQuery(
                        "SELECT r, u "
                        . "FROM MaclayServiceBundle:Record r "
                        . "JOIN r.student u "
                        . "WHERE u.id = :id "
                        . "ORDER BY r.dateCreated DESC"
                  )
                ->setMaxResults($length)
                ->setParameter("id", $userId)
                ->getResult();
                  
    }
}
