<?php

namespace Maclay\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    //incredibly inefficient way to do this... need to find a better way
    public function findByRole($role){
        $query = $this->getEntityManager()
                ->createQuery(
                        "SELECT u "
                        . "FROM MaclayServiceBundle:User u "
                  )
                ->getResult();
        
        foreach($query as $key => $user){
            $isRole = false;
            foreach($user->getRoles() as $r){
                if (strpos($r, $role) !== false){
                    $isRole = true;
                }
            }
            if ($isRole === false){
                unset($query[$key]);
            }
        }
        return $query;
    }
    
    public function getUninvitedUsers(){
        $query = $this->getEntityManager()
                ->createQuery(
                            "SELECT u"
                            . " FROM MaclayServiceBundle:User u "
                            . "WHERE u.isInvited = false"
                        )
                ->getResult();
        
        return $query;
        
    }
    
    public function getUsersForClub($grade, $gender){
        $query = $this->getEntityManager()
                ->createQuery(
                            "SELECT u "
                            . "FROM MaclayServiceBundle:User u "
                            . "JOIN u.studentinfo s "
                            . "WHERE s.grade = :grade AND s.gender = :gender"
                        )
                ->setParameter("grade", $grade)
                ->setParameter("gender", $gender)
                ->getResult();
        
        return $query;
    }
    
    public function getUserByStudentNumber($number){
        $query = $this->getEntityManager()
                ->createQuery(
                            "SELECT u "
                            . "FROM MaclayServiceBundle:User u "
                            . "JOIN u.studentinfo s "
                            . "WHERE s.studentNumber = :number"
                        )
                ->setParameter("number", $number)
                ->setMaxResults(1)
                ->execute();
        
        return $query;
    }
    
    public function getStudentsByLastName($lastName){
        $query = $this->getEntityManager()
                ->createQuery(
                            "SELECT u "
                            . "FROM MaclayServiceBundle:User u "
                            . "WHERE u. lastName LIKE :lastName"
                        )
                ->setParameter("lastName", $lastName)
                ->getResult();
        
        return $query;
    }
}
