Maclay\ServiceBundle\Entity\Club:
    type: entity
    table: null
    repositoryClass: Maclay\ServiceBundle\Entity\ClubRepository
    manyToMany: 
        members:
            targetEntity: User
            mappedBy: clubs
        sponsors:
            targetEntity: User
            inversedBy: sponsorForClubs
            joinTable:
                name: ClubSponsors
                joinColumns:
                    ClubID:
                        referencedColumnName: id
                inverseJoinColumns:
                    SponsorID:
                        referencedColumnName: id
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        clubName:
            type: string
            length: 255
            column: ClubName
    lifecycleCallbacks: {  }
