Maclay\ServiceBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: Maclay\ServiceBundle\Entity\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 255
            column: Description
    lifecycleCallbacks: {  }
