Maclay\ServiceBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Maclay\ServiceBundle\Entity\UserRepository
    manyToMany:
        clubs:
            targetEntity: Club
            inversedBy: members
            joinTable:
                name: ClubMembers
                joinColumns: 
                    MemberID: 
                        referencedColumnName: id
                inverseJoinColumns:
                    ClubID:
                        referencedColumnName: id
        sponsorForClubs:
            targetEntity: Club
            mappedBy: sponsors
        groups:
            targetEntity: Role
            joinTable:
                 name: UserRoles
                 joinColumns:
                     UserID:
                         referencedColumnName: id
                 inverseJoinColumns:
                     RoleID: 
                         referencedColumnName: id
        parents:
            targetEntity: User
            inversedBy: children
            joinTable:
                name: ParentChildInfo
                joinColumns:
                    ParentID: 
                        referencedColumnName: id
                inverseJoinColumns:
                    ChildID:
                        referencedColumnName: id
        children:
            targetEntity: User
            mappedBy: parents
        
    oneToMany:
        records:
            targetEntity: Record
            mappedBy: student
    oneToOne:
        studentinfo:
            targetEntity: StudentInfo
            mappedBy: student
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: FirstName
            nullable: TRUE
        lastName:
            type: string
            length: 255
            column: LastName
            nullable: TRUE
        middleName:
            type: string
            length: 255
            column: MiddleName
            nullable: TRUE
        tempPass:
            type: string
            length: 255
            column: TempPass
            nullable: TRUE
        isInvited:
            type: boolean
            column: IsInvited
        forgotPasswordCode:
            type: string
            length: 255
            column: ForgotPasswordCode
            nullable: TRUE
    lifecycleCallbacks: {  }
